# *** Generated by Zero [ please make sure that you have checked this file ] ***

FactoryBot.define do
  factory :foo do
    user
    name       :woo
    type       1
    activated  false
    # deleted_at { DateTime.now }
  end
end
