language: ruby

rvm:
  - 2.5.0

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install: gem install bundler -v 1.16.1

addons:
  postgresql: "10.4"
#  postgresql: "9.4"

services:
  - postgresql
#  - memcached
  - redis-server
#  - elasticsearch

env:
  global:
    - CC_TEST_REPORTER_ID=cd49d26b5c1dd48d2110be841080f089796b77e242e887d9cf9628f791fab741

before_install:
#  - sed -i "s/gems.ruby-china.org/rubygems.org/g" Gemfile.lock
#  - psql -c "CREATE USER \"admin\" WITH CREATEDB PASSWORD 'admin';" -U postgres
#  - psql -c "create database \"homeland-test\" WITH OWNER=\"admin\";" -U postgres
  - psql -c "create database zero_test;" -U postgres
  - cp config/database.yml.pg config/database.yml
  - cp config/settings.local.yml.example config/settings.local.yml
  - cp config/secrets.yml.example config/secrets.yml
#  - sed -i "s/SETUP_REDIS_HOST/127.0.0.1/g" config/redis.yml
#  - sed -i "s/SETUP_REDIS_PORT/6379/g" config/redis.yml

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
#  - bundle exec rubocop .
  - RAILS_ENV=test bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
