# *** Generated by Zero [ please make sure that you have checked this file ] ***

RSpec.describe Foo do
  let(:user) { create(:user) }
  let(:foo) { create(:foo) }
  subject { foo }

  describe '.ordered, [scope]' do
  end

  describe '.bar' do
  end

  describe '#change_status, change its online status' do
    context 'when there is no call to #page' do
      it { is_expected.to eq :success }
      it 'does something' do
        is_expected.to eq [1, 2, 3]
      end
    end
  end

  describe '#cool' do
  end
end
