# *** Generated by ZRO [ please make sure that you have checked this file ] ***

RSpec.describe Array do
  describe '#per' do
    subject { [1, 2, 3, 4, 5] }

    context 'when there is no call to #page' do
    end

    context 'when no args are passed' do
    end

    describe 'abnormal call' do
      context 'when pass illegal args' do
      end

      context 'when it is called many times' do
      end
    end
  end

  describe '#page' do

  end

  describe '#to_builder' do

  end


end
