module Generators::Jbuilder
  module Config
    cattr_accessor :enable do
      true
    end

    cattr_accessor :overwrite do
      false
    end

    cattr_accessor :templates do
      {
          index: (
          <<~FILE
        # *** Generated by ZRO [ please make sure that you have checked this file ] ***
        
        if @data.nil?
          unless @status
            error_class = Object.const_get("\#{controller_name.camelize}Error") rescue nil
            error_name  = "\#{action_name}_failed"
            if error_class.respond_to? error_name
              @error_info = error_class.send(error_name).info.values
            end
            @_code, @_msg = @error_info
          end
        
          json.partial! 'api/base', total: 0
          json.data @data || ''
        else
          json.partial! 'api/base', total: @data.size
        
          # @data = @data.page(@page).per(@row) if @page || @row
          # json.data @data.to_a.to_builder
          json.data @data.page(@page).per(@row).to_a.to_builder
        end
          FILE
          ),

          cache_index: (
          <<~FILE
        # *** Generated by ZRO [ please make sure that you have checked this file ] ***
        
        if @data.nil?
          unless @status
            error_class = Object.const_get("\#{controller_name.camelize}Error") rescue nil
            error_name  = "\#{action_name}_failed"
            if error_class.respond_to? error_name
              @error_info = error_class.send(error_name).info.values
            end
            @_code, @_msg = @error_info
          end
        
          json.partial! 'api/base', total: 0
          json.data @data || ''
        else
          json.partial! 'api/base', total: @data.size
          
          # @data = @data.page(@page).per(@row) if @page || @row
          json.cache! [ 'key' ], expires_in: 10.minutes do
            # json.data @data.to_a.to_builder
            json.data @data.page(@page).per(@row).to_a.to_builder
          end
        end
          FILE
          ),

          show: (
          <<~FILE
        # *** Generated by ZRO [ please make sure that you have checked this file ] ***
        
        json.partial! 'api/base', total: 1
        
        json.data @datum.respond_to?(:to_builder) ? @datum.to_builder : @datum
          FILE
          ),

          cache_show: (
          <<~FILE
        # *** Generated by ZRO [ please make sure that you have checked this file ] ***
        
        json.partial! 'api/base', total: 1
        
        json.cache! [ 'key' ], expires_in: 10.minutes do
          json.datum @datum.respond_to?(:to_builder) ? @datum.to_builder : @datum
        end
          FILE
          ),

          success: (
          <<~FILE
        # *** Generated by ZRO [ please make sure that you have checked this file ] ***
        
        json.partial! 'api/success'
          FILE
          ),

          success_or_not: (
          <<~FILE
        # *** Generated by ZRO [ please make sure that you have checked this file ] ***
        
        unless @status
          error_class = Object.const_get("\#{controller_name.camelize}Error") rescue nil
          error_name  = "\#{action_name}_failed"
          @error_info = error_class.send(error_name).info.values if error_class.respond_to? error_name
          @_code, @_msg = @error_info
        end
        
        json.partial! 'api/base', total: 0
        json.data @data || ''
          FILE
          ),
      }
    end
  end
end
