# *** Generated by Zero [ please make sure that you have checked this file ] ***

class CreateAdmins < ActiveRecord::Migration[5.1]
  def change
    create_table :admins, options: 'ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8' do |t|
      t.string   :name,            null: false
      t.string   :password_digest, null: false
      t.string   :email
      t.string   :phone_number
      t.datetime :deleted_at
    
      t.timestamps
    end
  end
end
